### PR TITLE
fix #66: SpanObserver doesn't prevent execution on failure

### LINKED ISSUE #66: SpanObserver failure should neither be propagated nor block other observers
Currently a throwing observer will block execution of the next, and the exception is propagated to the called. I would expect an error to be logged, but execution to be otherwise unaffected.

### PR DESCRIPTION
**Pull request by carterkozak**
An error is logged, and execution will continue, including other
SpanObservers registered to the Tracer.

### CODE REVIEW

File: tracing/src/main/java/com/palantir/tracing/Tracer.java [hunk 1]
```diff
@@ -252,7 +250,23 @@ public static synchronized SpanObserver unsubscribe(String name) {
     }
 
     private static void computeObserversList() {
-        observersList = ImmutableList.copyOf(observers.values());
+        Consumer<Span> newCompositeObserver = span -> { };
```
Comment (iamdanfox) [inline tracing/src/main/java/com/palantir/tracing/Tracer.java:253]: If we're micro-optimising, why do we tolerate calling the empty observer first and calling `andThen` on it?

Comment (carterkozak) [reply tracing/src/main/java/com/palantir/tracing/Tracer.java:253]: it's just a method invocation which is free compared to anything that does allocation (list iterator, for example).

Comment (carterkozak) [reply tracing/src/main/java/com/palantir/tracing/Tracer.java:253]: I can get rid of it, but I don't think it's worth the complexity since we won't be able to measure a difference.

**Review by iamdanfox — APPROVED** [review]
