### PR TITLE
[fix] Open a new span when wrapping with a new trace

### LINKED ISSUE #33: Creating a new trace should always open a new span
It should not be possible to create a new trace without also creating a root span. The current API allows for an undefined gap between creating a trace, and opening a span. In this gap, a `traceId` is set on the thread (and logged messages) without occurring inside of an observed operation.

### PR DESCRIPTION
**Pull request by pkoenig10**
## Before this PR
Creating a new trace does not create a new root span. Thus all top-level calls in this trace will have no parent span. This breaks assumptions of trace log consumers who assume that there is only one root span for a given trace.

This also seems counter to the `parentId` specification in the [Zipkin API](https://github.com/openzipkin/zipkin-api/blob/5fd719b114ff2ba44f1d2757888fa123cdfb0da6/zipkin-api.yaml#L353):
> The parent span ID or absent if this the root span in a trace.

## After this PR
Creating a new trace will create a new root span.

The issue is part of the `Major API revision` milestone, but this fix does not break the API. Is a major API revision required for this change?

### CODE REVIEW

**Review by uschi2000 — APPROVED** [review]
lgtm

File: tracing/src/main/java/com/palantir/tracing/Tracers.java [hunk 1]
```diff
@@ -148,8 +149,10 @@ public static ScheduledExecutorService wrapWithNewTrace(ScheduledExecutorService
 
             try {
                 Tracer.initTrace(Optional.empty(), Tracers.randomId());
+                Tracer.startSpan(ROOT_SPAN_OPERATION);
                 return delegate.call();
             } finally {
+                Tracer.completeSpan();
```
Comment (carterkozak) [inline tracing/src/main/java/com/palantir/tracing/Tracers.java]: fastCompleteSpan?

File: tracing/src/main/java/com/palantir/tracing/Tracers.java [hunk 2]
```diff
@@ -166,8 +169,10 @@ public static Runnable wrapWithNewTrace(Runnable delegate) {
 
             try {
                 Tracer.initTrace(Optional.empty(), Tracers.randomId());
+                Tracer.startSpan(ROOT_SPAN_OPERATION);
                 delegate.run();
             } finally {
+                Tracer.completeSpan();
```
Comment (carterkozak) [inline tracing/src/main/java/com/palantir/tracing/Tracers.java]: fastCompleteSpan

File: tracing/src/main/java/com/palantir/tracing/Tracers.java [hunk 3]
```diff
@@ -148,8 +149,10 @@ public static ScheduledExecutorService wrapWithNewTrace(ScheduledExecutorService
```
Comment (carterkozak) [inline tracing/src/main/java/com/palantir/tracing/Tracers.java:149]: Looks like there's an existing bug where wrapping a callable will leave an empty trace with no root span on the thread if there's not already an active trace.

`Tracer.getAndClearTrace` should probably return `Optional<Trace>`

Not related to this change though.

**Comment by carterkozak** [comment]
> The issue is part of the Major API revision milestone, but this fix does not break the API. Is a major API revision required for this change?

API rev isn't required for this change, but I don't think it solves the linked ticket. This definitely fixes a bug (thanks!), but it's still possible to invoke `Tracer.initTrace` without also creating a root span, which is what I'd like to target in a major version rev.

**Review by carterkozak — APPROVED** [review]
